# + -------------------------------------------------------------------------------- + #
# | BOT SETTINGS ( 봇 설정 )
# + -------------------------------------------------------------------------------- + #
BOT_TOKEN: "YOUR_TOKEN"

# + -------------------------------------------------------------------------------- + #
# | ACTIVITY SETTINGS ( 활동 설정 )
# + -------------------------------------------------------------------------------- + #
ACTIVITY_NAME: "YOUR_ACTIVITY_NAME"
ACTIVITY_TYPE: "playing"
STATUS: "ONLINE"

# + -------------------------------------------------------------------------------- + #
# | GUILD SETTINGS ( 길드 설정 )
# + -------------------------------------------------------------------------------- + #
GUILD_ID: "YOUR_GUILD_ID"

# + -------------------------------------------------------------------------------- + #
# | EMBED COLORS ( 임베드 색상 설정 )
# + -------------------------------------------------------------------------------- + #
EMBED_COLOR: "#fbb500"
EMBED_COLOR_SUCCESS: "#7eff8e"
EMBED_COLOR_ERROR: "#ff4b4b"

# + -------------------------------------------------------------------------------- + #
# | MONGODB SETTINGS ( 몽고DB 설정 )
# + -------------------------------------------------------------------------------- + #
database_settings:
  url: mongodb://localhost:27017
  database: eunhyun_bot

# + -------------------------------------------------------------------------------- + #
# | MONGODB COLLECTION SETTINGS ( 몽고DB Collection 설정 )
# + -------------------------------------------------------------------------------- + #
mongodb_collections:
  warn: "warn"
  ticket: "ticket"

# + -------------------------------------------------------------------------------- + #
# | LOG CHANNEL SETTINGS ( 로그 채널 설정 )
# + -------------------------------------------------------------------------------- + #
log_channel_settings:
  discrimination: 1276514316161384549

# + -------------------------------------------------------------------------------- + #
# | AUTO VOICE CHANNEL SETTINGS ( 자동 음성방 만들기 채널 설정 )
# + -------------------------------------------------------------------------------- + #
auto_voice_channel:
  source_voice_channel_id: 1276516253284175937
  source_voice_channel_name: "🔊・음성방 만들기"
  target_category_id: 1276526637332172884
  blacklist:
    - 1280264111107604570
    - 1280264148172935239
    - 1280264175527919719

# + -------------------------------------------------------------------------------- + #
# | TICKET CHANNEL SETTINGS ( 티켓 채널 설정 )
# + -------------------------------------------------------------------------------- + #
ticket_channel:
  target_category_id: 1276751474235412490

# + -------------------------------------------------------------------------------- + #
# | ROLE SELECT CHANNEL SETTINGS ( 역할 선택 채널 설정 )
# + -------------------------------------------------------------------------------- + #
role_select_channel_settings:
  channel_id: 1276872259880878110
  age_message_id: 1277149101028413544
  gender_message_id: 1277203321412653117
  valorant_tier_message_id: 1280260634289766451
  verify_message_id: 1280537775451672668

# + -------------------------------------------------------------------------------- + #
# | JOIN MESSAGE CHANNEL SETTINGS ( 입장 메시지 채널 설정 )
# + -------------------------------------------------------------------------------- + #
join_message_channel:
  channel_id: 1282136507775189032
  rule_channel_id: 1276510089460584459
  main_chat_channel_id: 1281350464352288809