# + -------------------------------------------------------------------------------- + #
# | BOT SETTINGS ( 봇 설정 )
# + -------------------------------------------------------------------------------- + #
BOT_TOKEN: "YOUR_TOKEN"

# + -------------------------------------------------------------------------------- + #
# | ACTIVITY SETTINGS ( 활동 설정 )
# + -------------------------------------------------------------------------------- + #
ACTIVITY_NAME: "YOUR_ACTIVITY_NAME"
ACTIVITY_TYPE: "playing"
STATUS: "ONLINE"

# + -------------------------------------------------------------------------------- + #
# | EMBED COLORS ( 임베드 색상 설정 )
# + -------------------------------------------------------------------------------- + #
EMBED_COLOR: "#fbb500"
EMBED_COLOR_SUCCESS: "#7eff8e"
EMBED_COLOR_ERROR: "#ff4b4b"

GUILD_ID: "YOUR_GUILD_ID"